/// <reference types="@sveltejs/kit" />
/// <reference lib="webworker" />
import { build, files, version } from '$service-worker';

const ASSETS = `cache${version}`;
const RUNTIME = `runtime${version}`;
const QUEUE_DB = 'offline-queue';
const QUEUE_STORE = 'requests';

// `build` is files generated by the SvelteKit build process
// `files` is static assets in the project
const to_cache = build.concat(files);
const staticAssets = new Set(to_cache);

self.addEventListener('install', (event: any) => {
	event.waitUntil(
		caches
			.open(ASSETS)
			.then((cache) => cache.addAll(to_cache))
			.then(() => (self as any).skipWaiting())
	);
});

self.addEventListener('activate', (event: any) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== ASSETS && key !== RUNTIME) await caches.delete(key);
			}
			(self as any).clients.claim();
		})
	);
});

// ---------- Offline queue (IndexedDB) ----------
function openQueueDb(): Promise<IDBDatabase> {
	return new Promise((resolve, reject) => {
		const req = indexedDB.open(QUEUE_DB, 1);
		req.onupgradeneeded = () => {
			const db = req.result;
			if (!db.objectStoreNames.contains(QUEUE_STORE)) {
				db.createObjectStore(QUEUE_STORE, { keyPath: 'id', autoIncrement: true });
			}
		};
		req.onsuccess = () => resolve(req.result);
		req.onerror = () => reject(req.error);
	});
}

async function enqueueRequest(request: Request): Promise<void> {
	try {
		const db = await openQueueDb();
		const clone = request.clone();
		const body = await clone.text();
		const tx = db.transaction(QUEUE_STORE, 'readwrite');
		tx.objectStore(QUEUE_STORE).add({
			url: request.url,
			method: request.method,
			headers: Array.from(request.headers.entries()),
			body,
			queued_at: Date.now(),
		});
	} catch {
		// Queue failure is non-fatal; request is dropped
	}
}

async function replayQueue(): Promise<void> {
	let db: IDBDatabase;
	try {
		db = await openQueueDb();
	} catch {
		return;
	}
	const tx = db.transaction(QUEUE_STORE, 'readwrite');
	const store = tx.objectStore(QUEUE_STORE);
	const all = await new Promise<{ id: number; url: string; method: string; headers: [string, string][]; body: string }[]>((resolve, reject) => {
		const req = store.getAll();
		req.onsuccess = () => resolve(req.result as any);
		req.onerror = () => reject(req.error);
	});
	for (const item of all) {
		try {
			await fetch(item.url, {
				method: item.method,
				headers: Object.fromEntries(item.headers),
				body: item.method !== 'GET' ? item.body : undefined,
			});
			store.delete(item.id);
		} catch {
			// Leave in queue, retry next time
		}
	}
}

// Try to replay the queue whenever the SW takes control (online again)
self.addEventListener('message', (event: any) => {
	if (event.data?.type === 'REPLAY_QUEUE') {
		replayQueue();
	}
});

// Also attempt replay on activation (browser is online by definition of reaching sw)
self.addEventListener('activate', (event: any) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== ASSETS && key !== RUNTIME) await caches.delete(key);
			}
			(self as any).clients.claim();
		}).then(() => replayQueue())
	);
});

// ---------- Fetch handling ----------
async function networkFirst(request: Request): Promise<Response> {
	const cache = await caches.open(ASSETS);
	try {
		const response = await fetch(request);
		if (response.status === 200) {
			cache.put(request, response.clone());
		}
		return response;
	} catch {
		const cached = await cache.match(request);
		if (cached) return cached;
		if (request.mode === 'navigate') {
			const root = await cache.match('/');
		return root || new Response('Offline', { status: 503 });
		}
		return new Response('Offline', { status: 503 });
	}
}

async function staleWhileRevalidate(request: Request): Promise<Response> {
	const cache = await caches.open(RUNTIME);
	const cached = await cache.match(request);
	// Return cached immediately (if any), refresh in background
	const network = fetch(request)
		.then((response) => {
			if (response.status === 200) {
				cache.put(request, response.clone());
			}
			return response;
		})
		.catch(() => cached || new Response('Offline', { status: 503 }));
	return cached || network;
}

self.addEventListener('fetch', (event: any) => {
	const url = new URL(event.request.url);

	// Only handle same-origin
	if (url.origin !== location.origin) return;

	// Non-GET methods: try network, queue on failure
	if (event.request.method !== 'GET') {
		event.respondWith(
			fetch(event.request).catch(() => {
				enqueueRequest(event.request).then(() => {
					return new Response(JSON.stringify({ success: false, error: 'offline-queued' }), {
						status: 202,
						headers: { 'Content-Type': 'application/json' },
					});
				});
			})
		);
		return;
	}

	// API GET: stale-while-revalidate (offline-friendly reads)
	if (url.pathname.startsWith('/api/')) {
		event.respondWith(staleWhileRevalidate(event.request));
		return;
	}

	// Static assets: cache-first
	if (staticAssets.has(url.pathname)) {
		event.respondWith(caches.match(event.request));
		return;
	}

	// Page requests: network-first with cache fallback
	event.respondWith(networkFirst(event.request));
});