/// <reference types="@sveltejs/kit" />
import { build, files, version } from '$service-worker';

const ASSETS = `cache${version}`;

// `build` is files generated by the SvelteKit build process
// `files` is static assets in the project
const to_cache = build.concat(files);
const staticAssets = new Set(to_cache);

self.addEventListener('install', (event: ExtendableEvent) => {
	event.waitUntil(
		caches
			.open(ASSETS)
			.then((cache) => cache.addAll(to_cache))
			.then(() => (self as any as ServiceWorkerGlobalScope).skipWaiting())
	);
});

self.addEventListener('activate', (event: ExtendableEvent) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== ASSETS) await caches.delete(key);
			}
			(self as any as ServiceWorkerGlobalScope).clients.claim();
		})
	);
});

async function fetchAndCache(request: Request) {
	const cache = await caches.open(ASSETS);
	try {
		const response = await fetch(request);
		if (response.status === 200) {
			cache.put(request, response.clone());
		}
		return response;
	} catch {
		const cached = await cache.match(request);
		if (cached) return cached;
		// For navigation requests, return the cached root page as fallback
		if (request.mode === 'navigate') {
			return cache.match('/');
		}
		return new Response('Offline', { status: 503 });
	}
}

self.addEventListener('fetch', (event: FetchEvent) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Only handle same-origin
	if (url.origin !== location.origin) return;

	// For API requests, network-only (don't cache API)
	if (url.pathname.startsWith('/api/')) {
		event.respondWith(fetch(event.request));
		return;
	}

	// For page requests, network-first with cache fallback
	event.respondWith(fetchAndCache(event.request));
});
